"""Object storage for uploaded documents.

Keys are generated by the server ("<user_id>/<document_id>") and never come from a filename.
Both backends are swappable behind the same three methods.
"""

import os
from pathlib import Path
from typing import Optional, Protocol

import httpx

from app.core.config import get_settings
from app.core.security import decrypt_bytes, encrypt_bytes


class StorageError(Exception):
    """Raised with a user-safe message."""


class StorageBackend(Protocol):
    name: str

    def save(self, key: str, data: bytes, content_type: str) -> None: ...

    def load(self, key: str) -> bytes: ...

    def delete(self, key: str) -> None: ...


class LocalEncryptedStorage:
    """Files on local disk, encrypted with the server's Fernet key. For development and single-server use."""

    name = "local"

    def __init__(self, root: str):
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        # Defence in depth: keys are server-generated, but never allow escaping the root
        if self.root not in path.parents:
            raise StorageError("Invalid storage key.")
        return path

    def save(self, key: str, data: bytes, content_type: str) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(".tmp")
        tmp.write_bytes(encrypt_bytes(data))
        os.replace(tmp, path)

    def load(self, key: str) -> bytes:
        try:
            return decrypt_bytes(self._path(key).read_bytes())
        except FileNotFoundError as exc:
            raise StorageError("The stored file could not be found.") from exc

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


class SupabaseStorage:
    """Supabase Storage (private bucket). The service role key stays on the server."""

    name = "supabase"

    def __init__(self, url: str, service_key: str, bucket: str, transport: Optional[httpx.BaseTransport] = None):
        self.base = f"{url.rstrip('/')}/storage/v1/object"
        self.bucket = bucket
        self.headers = {"Authorization": f"Bearer {service_key}", "apikey": service_key}
        self._transport = transport

    def _http(self) -> httpx.Client:
        return httpx.Client(timeout=30, transport=self._transport, headers=self.headers)

    def save(self, key: str, data: bytes, content_type: str) -> None:
        with self._http() as http:
            r = http.post(
                f"{self.base}/{self.bucket}/{key}",
                content=data,
                headers={"Content-Type": content_type, "x-upsert": "false"},
            )
        if r.status_code not in (200, 201):
            raise StorageError("The file could not be stored. Please try again.")

    def load(self, key: str) -> bytes:
        with self._http() as http:
            r = http.get(f"{self.base}/authenticated/{self.bucket}/{key}")
        if r.status_code != 200:
            raise StorageError("The stored file could not be loaded.")
        return r.content

    def delete(self, key: str) -> None:
        with self._http() as http:
            r = http.request("DELETE", f"{self.base}/{self.bucket}", json={"prefixes": [key]})
        if r.status_code not in (200, 204, 404):
            raise StorageError("The stored file could not be deleted.")


class DatabaseEncryptedStorage:
    """Files in the application database, encrypted with the server's Fernet key.

    Survives restarts on hosts with a temporary disk and needs no extra service or key.
    Uses its own short session, so a stored file does not depend on the caller's transaction.
    """

    name = "database"

    def save(self, key: str, data: bytes, content_type: str) -> None:
        from app.core.database import SessionLocal
        from app.models import StoredFile

        try:
            with SessionLocal() as db:
                db.merge(StoredFile(key=key, content_type=content_type, data=encrypt_bytes(data)))
                db.commit()
        except Exception as exc:  # never include the content in the error
            raise StorageError("The file could not be stored. Please try again.") from exc

    def load(self, key: str) -> bytes:
        from app.core.database import SessionLocal
        from app.models import StoredFile

        with SessionLocal() as db:
            row = db.get(StoredFile, key)
            if row is None:
                raise StorageError("The stored file could not be found.")
            return decrypt_bytes(row.data)

    def delete(self, key: str) -> None:
        from app.core.database import SessionLocal
        from app.models import StoredFile

        with SessionLocal() as db:
            db.query(StoredFile).filter(StoredFile.key == key).delete()
            db.commit()


_backend: Optional[StorageBackend] = None


def get_storage() -> StorageBackend:
    global _backend
    if _backend is None:
        s = get_settings()
        if s.storage_backend == "supabase":
            if not (s.supabase_url and s.supabase_service_role_key):
                raise StorageError("Supabase Storage is selected but not configured.")
            _backend = SupabaseStorage(s.supabase_url, s.supabase_service_role_key, s.supabase_bucket)
        elif s.storage_backend == "database":
            _backend = DatabaseEncryptedStorage()
        else:
            _backend = LocalEncryptedStorage(s.storage_dir)
    return _backend


def set_storage(backend: Optional[StorageBackend]) -> None:
    """Used by tests to inject a backend (or reset to the configured one with None)."""
    global _backend
    _backend = backend
