"""English / Indonesian text generated by the server.

The frontend sends the chosen language in the X-Language header. A middleware stores it for the
current request, and tr("English", "Indonesia") returns the matching text. Text is written in place,
so both versions sit side by side.

Messages meant for other people (drafts, questions) are always English: they are built inside
`with language("en")`.
"""

from contextlib import contextmanager
from contextvars import ContextVar
from typing import Iterator

LANGUAGES = ("en", "id")
_current: ContextVar[str] = ContextVar("language", default="en")


def get_language() -> str:
    return _current.get()


def set_language(lang: str | None) -> None:
    _current.set(lang if lang in LANGUAGES else "en")


def tr(en: str, id: str) -> str:
    """The text for the request's language. Named tr, not t: t is a common loop variable here."""
    return id if _current.get() == "id" else en


@contextmanager
def language(lang: str) -> Iterator[None]:
    """Temporarily use one language, e.g. English for a message that is sent to someone else."""
    token = _current.set(lang if lang in LANGUAGES else "en")
    try:
        yield
    finally:
        _current.reset(token)


def request_language(header: str | None) -> str:
    """X-Language wins. Without it the server answers in English."""
    value = (header or "").strip().lower()[:2]
    return value if value in LANGUAGES else "en"
